# Generated by Django 6.0.1 on 2026-01-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDelivery',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=25)),
                ('order', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('mobileno', models.IntegerField()),
                ('deliverycharge', models.FloatField()),
            ],
        ),
    ]
